name: QA

on: [push, pull_request]

jobs:
  qa:
    name: QA
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [ '14.x', '16.x', '18.x' ]
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        npm install
    - name: Run roboter
      run: |
        npm test
